# Generated by Django 6.0.5 on 2026-05-10 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('date', models.DateField(verbose_name='Дата проведения')),
                ('description', models.TextField(verbose_name='Описание')),
                ('max_teams', models.PositiveIntegerField(default=16, verbose_name='Максимум команд')),
                ('regulation_file', models.FileField(blank=True, null=True, upload_to='regulations/', verbose_name='Положение турнира')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Турнир',
                'verbose_name_plural': 'Турниры',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='TournamentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.PositiveIntegerField(verbose_name='Место')),
                ('team_name', models.CharField(max_length=200, verbose_name='Команда')),
                ('score', models.CharField(blank=True, max_length=100, verbose_name='Счёт / результат')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='tournaments.tournament', verbose_name='Турнир')),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результаты',
                'ordering': ['place'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрена'), ('rejected', 'Отклонена')], default='pending', max_length=20, verbose_name='Статус')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи')),
                ('player1_name', models.CharField(max_length=200, verbose_name='ФИО участника 1')),
                ('player1_dob', models.DateField(verbose_name='Дата рождения участника 1')),
                ('player1_phone', models.CharField(max_length=20, verbose_name='Телефон участника 1')),
                ('player1_city', models.CharField(max_length=100, verbose_name='Город участника 1')),
                ('player2_name', models.CharField(max_length=200, verbose_name='ФИО участника 2')),
                ('player2_dob', models.DateField(verbose_name='Дата рождения участника 2')),
                ('player2_phone', models.CharField(max_length=20, verbose_name='Телефон участника 2')),
                ('player2_city', models.CharField(max_length=100, verbose_name='Город участника 2')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='tournaments.tournament', verbose_name='Турнир')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-submitted_at'],
                'constraints': [models.UniqueConstraint(fields=('tournament', 'player1_phone', 'player2_phone'), name='unique_application_per_tournament')],
            },
        ),
    ]
