# Generated by Django 4.2.29 on 2026-05-10 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentresult',
            name='team_name',
        ),
        migrations.AddField(
            model_name='tournamentresult',
            name='players',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='tournaments.application', verbose_name='Игроки'),
        ),
        migrations.AlterField(
            model_name='application',
            name='player1_city',
            field=models.CharField(max_length=100, verbose_name='Город (1)'),
        ),
        migrations.AlterField(
            model_name='application',
            name='player1_dob',
            field=models.DateField(verbose_name='Дата рождения (1)'),
        ),
        migrations.AlterField(
            model_name='application',
            name='player1_name',
            field=models.CharField(max_length=200, verbose_name='ФИО (1)'),
        ),
        migrations.AlterField(
            model_name='application',
            name='player1_phone',
            field=models.CharField(max_length=20, verbose_name='Номер телефона (1)'),
        ),
        migrations.AlterField(
            model_name='application',
            name='player2_city',
            field=models.CharField(max_length=100, verbose_name='Город (2)'),
        ),
        migrations.AlterField(
            model_name='application',
            name='player2_dob',
            field=models.DateField(verbose_name='Дата рождения (2)'),
        ),
        migrations.AlterField(
            model_name='application',
            name='player2_name',
            field=models.CharField(max_length=200, verbose_name='ФИО (2)'),
        ),
        migrations.AlterField(
            model_name='application',
            name='player2_phone',
            field=models.CharField(max_length=20, verbose_name='Номер телефона (2)'),
        ),
    ]
