# Generated by Django 6.0.5 on 2026-06-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_remove_tournamentresult_team_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='place',
            field=models.CharField(blank=True, default='', help_text='Например: 1, 2, 3, 6-7 (если место делится между несколькими парами)', max_length=10, verbose_name='Место'),
        ),
    ]
