# Generated by Django 6.0.5 on 2026-06-15 20:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_application_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='place',
            field=models.CharField(blank=True, default='', help_text='Число или диапазон через тире, например: 1, 1-2, 9, 11-12', max_length=10, validators=[django.core.validators.RegexValidator(message='Введите число или диапазон через тире, например: 1, 9, 11-12', regex='^\\d{1,3}(-\\d{1,3})?$')], verbose_name='Место'),
        ),
    ]
