# Generated by Django 6.0.5 on 2026-05-10 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True, verbose_name='Номер корта')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Корт',
                'verbose_name_plural': 'Корты',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='RecurringBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='День недели')),
                ('start_time', models.TimeField(verbose_name='Начало')),
                ('end_time', models.TimeField(verbose_name='Конец')),
                ('label', models.CharField(blank=True, max_length=100, verbose_name='Подпись (что за тренировка)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_blocks', to='training.court', verbose_name='Корт')),
            ],
            options={
                'verbose_name': 'Постоянная блокировка',
                'verbose_name_plural': 'Постоянные блокировки',
            },
        ),
        migrations.CreateModel(
            name='TrainingBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('start_slot', models.TimeField(verbose_name='Начало (слот)')),
                ('end_slot', models.TimeField(verbose_name='Конец (слот)')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='training.court', verbose_name='Корт')),
            ],
            options={
                'verbose_name': 'Запись на тренировку',
                'verbose_name_plural': 'Записи на тренировки',
                'ordering': ['date', 'start_slot'],
            },
        ),
    ]
