# Generated by Django 6.0.5 on 2026-05-11 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название площадки')),
                ('description', models.TextField(blank=True, default='Информация о площадке')),
            ],
        ),
        migrations.AlterModelOptions(
            name='court',
            options={'ordering': ['number'], 'verbose_name': 'Площадка', 'verbose_name_plural': 'Площадки'},
        ),
        migrations.AlterModelOptions(
            name='recurringblock',
            options={'verbose_name': 'Постоянная тренировка', 'verbose_name_plural': 'Постоянные тренировки'},
        ),
        migrations.AlterField(
            model_name='court',
            name='number',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='Номер площадки'),
        ),
        migrations.AlterField(
            model_name='recurringblock',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_blocks', to='training.court', verbose_name='Площадка'),
        ),
        migrations.AlterField(
            model_name='trainingbooking',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='training.court', verbose_name='Площадка'),
        ),
    ]
