# Generated by Django 6.0.5 on 2026-05-11 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_venueinfo_alter_court_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venueinfo',
            options={'verbose_name': 'Информация', 'verbose_name_plural': 'Информации'},
        ),
    ]
